//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIAppsistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asistente()
        {
            this.Calificaciones = new HashSet<Calificaciones>();
            this.ContratosXAsistente = new HashSet<ContratosXAsistente>();
            this.HabilidadesXAsistente = new HashSet<HabilidadesXAsistente>();
            this.TipoPagoXAsistente = new HashSet<TipoPagoXAsistente>();
            this.Transaccion = new HashSet<Transaccion>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Genero { get; set; }
        public string Celular { get; set; }
        public string Identificacion { get; set; }
        public Nullable<int> Tipo_Identificacion { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Certificado_Asistente { get; set; }
        public Nullable<int> ID_Licencia_Conducir { get; set; }
        public int Tiempo_Laborado { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> CobroXhora { get; set; }
        public string Foto { get; set; }
    
        public virtual Licencias Licencias { get; set; }
        public virtual Identificacion Identificacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratosXAsistente> ContratosXAsistente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HabilidadesXAsistente> HabilidadesXAsistente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoPagoXAsistente> TipoPagoXAsistente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
