//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIAppsistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesXContrato
    {
        public int ID { get; set; }
        public int ID_Contrato { get; set; }
        public string Detalle { get; set; }
    
        public virtual ContratosXAsistente ContratosXAsistente { get; set; }
    }
}
